---
- name: Provision EC2 Instances
  hosts: localhost
  tasks:
    - name: Launch EC2 database instance
      amazon.aws.ec2_instance:
        key_name: rachykey
        instance_type: t2.micro
        image_id: ami-0aff18ec83b712f05
        wait: yes
        region: us-west-2
        count: 1
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 20  # Specify the desired volume size in GB
        tags:
          Name: KasmDBServer
      register: ec2_db

    - name: Launch EC2 web instance
      amazon.aws.ec2_instance:
        key_name: rachykey
        instance_type: t2.micro
        image_id: ami-0aff18ec83b712f05
        wait: yes
        region: us-west-2
        count: 1
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 20  # Specify the desired volume size in GB
        tags:
          Name: KasmWebServer
      register: ec2_web

    - name: Launch EC2 agent instance
      amazon.aws.ec2_instance:
        key_name: rachykey
        instance_type: t2.micro
        image_id: ami-0aff18ec83b712f05
        wait: yes
        region: us-west-2
        count: 1
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 20  # Specify the desired volume size in GB
        tags:
          Name: KasmAgentServer
      register: ec2_agent

    - name: Launch EC2 Guacamole instance
      amazon.aws.ec2_instance:
        key_name: rachykey
        instance_type: t2.micro
        image_id: ami-0aff18ec83b712f05
        wait: yes
        region: us-west-2
        count: 1
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 20  # Specify the desired volume size in GB
        tags:
          Name: KasmGuacServer
      register: ec2_guac

    - name: Output configuration for Ansible inventory
      debug:
        msg: |
          ##################
          # Host inventory #
          ##################
          all:
            children:
              zone1:
                children:
                  zone1_db:
                    hosts:
                      zone1_db_1:
                        ansible_host: {{ ec2_db.instances[0].public_dns_name }}
                        ansible_port: 22
                        ansible_ssh_user: ubuntu
                        ansible_ssh_private_key_file: rachykey.pem
                  zone1_web:
                    hosts:
                      zone1_web_1:
                        ansible_host: {{ ec2_web.instances[0].public_dns_name }}
                        ansible_port: 22
                        ansible_ssh_user: ubuntu
                        ansible_ssh_private_key_file: rachykey.pem
                  zone1_agent:
                    hosts:
                      zone1_agent_1:
                        ansible_host: {{ ec2_agent.instances[0].public_dns_name }}
                        ansible_port: 22
                        ansible_ssh_user: ubuntu
                        ansible_ssh_private_key_file: rachykey.pem
                  zone1_guac:
                    hosts:
                      zone1_guac_1:
                        ansible_host: {{ ec2_guac.instances[0].public_dns_name }}
                        ansible_port: 22
                        ansible_ssh_user: ubuntu
                        ansible_ssh_private_key_file: rachykey.pem

